[package]
name = "rs_helixmarkets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.7"
hex = "0.4.3"
secp256k1 = "0.28.2"
sha2 = "0.10.8"
